### ISSUE TITLE
Update the `attach()` function w.r.t to the addition of the `DetachHash` enum in pallet-detach

### ISSUE THREAD

**Issue by aang114** [fragcolor-xyz/fragnova-contracts#18]
This is how `DetachHash` looks like now: https://github.com/fragcolor-xyz/clamor/blob/devel/pallets/detach/src/lib.rs#L88-L106

This is the `attach()` function: https://github.com/fragcolor-xyz/hasten-contracts/blob/clamor/contracts/Fragment.sol#L259

**Comment by aang114** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/hasten-contracts/18?planning-poker) with Zenhub @sinkingsugar

**Comment by aang114** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/hasten-contracts/18?planning-poker) with Zenhub @alebaffa

**Comment by sinkingsugar** [comment]
Bump, what's this @aang114 ?
