### ISSUE TITLE
Fix lock and unlock

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/fragnova-contracts#19]
At the moment a user can lock an amount Y1 of FRAG for X1 time, then lock a new amount Y2 (>Y1) for X2 time (<X1) and transfer the total amount Y1+Y2. 

Note: in Clamor side two subsequent locks are handled as separate events and so the amount of Tickets and NOVA released depends on the amount locked in each lock event, considering also the amount of time passed between their lock time (i.e. block in Clamor) and the current block.

**Comment by sinkingsugar** [comment]
This is done right? Just missing the timestamp or whatever we wanna do @alebaffa

**Comment by alebaffa** [comment]
Yes this is done.
