### ISSUE TITLE
Implement tokenURI for PreERC721

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/fragnova-contracts#2]
https://github.com/sinkingsugar/hasten-contracts/blob/df8f2cc9f58fbc52d05c9b403a67584ceec047b1/contracts/PreERC721.sol#L69

**Comment by alebaffa** [comment]
@sinkingsugar do we still want this?

**Comment by sinkingsugar** [comment]
Not really, gas is cheap etc
